work_dir: ./work_dir/p2a-v2/ase_train

# feeder
feeder: feeders.feeder.Feeder

train_feeder_args: # fake train args for running the test
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v2/train_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v2/train_label.pkl

test_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v2/val_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v2/val_label.pkl
# model
model: model.network.Model
model_args:
  in_channels: 12
  num_class: 14
  num_point: 17
  num_person: 2
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.pingpong_coco.AdjMatrixGraph

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [ 30,40,50 ]

num_epoch: 60
device: [ 0 ]
batch_size: 40
forward_batch_size: 40
test_batch_size: 40
nesterov: True

optimizer: SGD

eval_start: 5
eval_interval: 5

phase: test
weights: ./work_dir/pingpong-star-challenge/ase_train/2024-02-02T19-21-06/weights/weights-epoch-best_model_40.pt
save_score: True
